spring.application.name=arvore-geneologia-pro

# Conexão mapeada pelas variáveis unificadas do painel da Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativação do Flyway, ativado
spring.flyway.enabled=true

# Porta Dinâmica da Railway (Resolve o erro 502 Bad Gateway)
server.port=${PORT:8080}
server.address=0.0.0.0

# Configurações do Token JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Configurações do Pool de Conexões (Hikari)
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# LOGS REATIVADOS: Essencial para acompanhar a inicialização completa
logging.level.root=INFO
logging.level.org.springframework=INFO
